def test_case_training_section_functionality(app):
    app.orangeHrm.open_application_and_login()
    app.orangeHrm.sideMenu.click_on_side_menu_button("Training")
    app.orangeHrm.training.wait_for_page_loading()
    app.orangeHrm.step.switch_to_iframe(app.orangeHrm.training.iframe)
    app.orangeHrm.training.click_on_filter_button()
    app.orangeHrm.popUp.training_filter.set_coordinator('Aaron Hamilton')
    app.orangeHrm.popUp.click_on_filter_search_button()
    app.orangeHrm.training.wait_for_table_reload()
    list_before_add_event = app.orangeHrm.training.table.get_column_data('title')
    app.orangeHrm.training.click_on_add_course_button()
    app.orangeHrm.training.wait_for_page_loading()
    app.orangeHrm.training.set_course_title(course_title)
    list_containing_new_course = list_before_add_event + [course_title]
    app.orangeHrm.training.set_course_coordinator("Aaron Hamilton")
    app.orangeHrm.training.click_on_save_button()
    app.orangeHrm.sideMenu.click_on_side_menu_button("Training")
    app.orangeHrm.training.wait_for_page_loading()
    app.orangeHrm.training.click_on_filter_button()
    app.orangeHrm.popUp.training_filter.set_coordinator('Aaron Hamilton')
    app.orangeHrm.popUp.click_on_filter_search_button()
    app.orangeHrm.training.wait_for_table_reload()
    list_after_add_event = app.orangeHrm.training.table.get_column_data('title')
    app.assert_that(sorted(list_containing_new_course)).is_equal_to(sorted(list_after_add_event))